- name: deepseek-chat
  model: deepseek-chat
  options:
      systemMessageRole: system

- name: deepseek-reasoner
  model: deepseek-reasoner
  options:
      systemMessageRole: system
      supportsTools: false
