- name: gpt-4.1
  model: gpt-4.1

- name: gpt-4.1-mini
  model: gpt-4.1-mini

- name: gpt-4.1-nano
  model: gpt-4.1-nano

- name: o3
  model: o3-2025-04-16
  options:
      minimumTempature: 1.0

- name: o3-mini
  model: o3-mini-2025-01-31
  options:
      minimumTempature: 1.0

- name: o4-mini
  model: o4-mini-2025-04-16
  options:
      minimumTempature: 1.0
