- name: gpt-4o
  model: gpt-4o-2024-08-06

- name: gpt-4o-mini
  model: gpt-4o-mini-2024-07-18

- name: gpt-4
  model: gpt-4

- name: gpt-4.5
  model: gpt-4.5-preview-2025-02-27

- name: o1
  model: o1-2024-12-17
  options:
      supportsStreaming: false
      minimumTempature: 1.0

- name: o1-preview
  model: o1-preview-2024-09-12
  options:
      systemMessageRole: user
      supportsTools: false
      minimumTempature: 1.0

- name: o1-mini
  model: o1-mini-2024-09-12
  options:
      systemMessageRole: user
      supportsTools: false
      minimumTempature: 1.0

- name: o3-mini
  model: o3-mini-2025-01-31
  options:
      minimumTempature: 1.0
