- name: gpt-5
  model: gpt-5-2025-08-07
  options:
      minimumTemperature: 1.0

- name: gpt-5-mini
  model: gpt-5-mini-2025-08-07
  options:
      minimumTemperature: 1.0

- name: gpt-5-nano
  model: gpt-5-nano-2025-08-07
  options:
      minimumTemperature: 1.0
