languages:
    - name: typescript
      extensions:
          - .ts
          - .js
          - .ts
          - .jsx
      queries:
          type: { include: ./languages/typescript/type.scm }
          var: { include: ./languages/typescript/var.scm }
          class: { include: ./languages/typescript/class.scm }
          method: { include: ./languages/typescript/method.scm }
          function: { include: ./languages/typescript/function.scm }
          named-arrow-function: { include: ./languages/typescript/named-arrow-function.scm }

    - name: go
      extensions:
          - .go
      queries:
          type: { include: ./languages/go/type.scm }
          var: { include: ./languages/go/var.scm }
          func: { include: ./languages/go/func.scm }
          named-func-expr: { include: ./languages/go/named-func-expr.scm }
