languages:
    - name: typescript
      extensions:
          - .ts
          - .js
          - .ts
          - .jsx
      queries:
          type: { include: ./languages/typescript/type.query }
          var: { include: ./languages/typescript/var.query }
          class: { include: ./languages/typescript/class.query }
          method: { include: ./languages/typescript/method.query }
          function: { include: ./languages/typescript/function.query }
          named-arrow-function: { include: ./languages/typescript/named-arrow-function.query }

    - name: go
      extensions:
          - .go
      queries:
          type: { include: ./languages/go/type.query }
          var: { include: ./languages/go/var.query }
          func: { include: ./languages/go/func.query }
          named-func-expr: { include: ./languages/go/named-func-expr.query }
