languages:
    - name: typescript
      extensions:
          - .ts
          - .js
          - .ts
          - .jsx
      queries:
          type: { include: ./languages/typescript/type.scm }
          var: { include: ./languages/typescript/var.scm }
          class: { include: ./languages/typescript/class.scm }
          method: { include: ./languages/typescript/method.scm }
          function: { include: ./languages/typescript/function.scm }
          named-arrow-function: { include: ./languages/typescript/named-arrow-function.scm }

    - name: go
      extensions:
          - .go
      queries:
          type: { include: ./languages/go/type.scm }
          var: { include: ./languages/go/var.scm }
          func: { include: ./languages/go/func.scm }
          named-func-expr: { include: ./languages/go/named-func-expr.scm }

    - name: java
      extensions:
          - .java
      queries:
          class: { include: ./languages/java/class.scm }
          interface: { include: ./languages/java/interface.scm }
          enum: { include: ./languages/java/enum.scm }
          method: { include: ./languages/java/method.scm }
          field: { include: ./languages/java/field.scm }
          lambda: { include: ./languages/java/lambda.scm }
