languages:
    - name: typescript
      extensions:
          - .ts
          - .js
          - .ts
          - .jsx
      queries:
          function: { include: ./languages/typescript/function.query }
          method: { include: ./languages/typescript/method.query }
          variable: { include: ./languages/typescript/variable.query }
          interface: { include: ./languages/typescript/interface.query }
          type: { include: ./languages/typescript/type.query }
          class: { include: ./languages/typescript/class.query }

    - name: go
      extensions:
          - .go
      queries:
          function: { include: ./languages/go/function.query }
          method: { include: ./languages/go/method.query }
          variable: { include: ./languages/go/variable.query }
          type: { include: ./languages/go/type.query }
