defaultModel: sonnet
reprompterModel: haiku
embeddingsModel: mxbai-embed-large
summarizerModel: gpt-4o-mini
webTranslatorModel: gpt-4o-mini
providers:
    Anthropic:
        - name: haiku
          model: claude-3-haiku-20240307
        - name: sonnet
          model: claude-3-7-sonnet-20250219
        - name: opus
          model: claude-3-opus-20240229
    OpenAI:
        - name: gpt-4o
          model: gpt-4o-2024-08-06
        - name: gpt-4o-mini
          model: gpt-4o-mini-2024-07-18
        - name: gpt-4
          model: gpt-4
        - name: gpt-4.5
          model: gpt-4.5-preview-2025-02-27
        - name: o1
          model: o1-2024-12-17
          options:
              supportsStreaming: false
              minimumTempature: 1.0
        - name: o1-preview
          model: o1-preview-2024-09-12
          options:
              systemMessageRole: user
              supportsTools: false
              minimumTempature: 1.0
        - name: o1-mini
          model: o1-mini-2024-09-12
          options:
              systemMessageRole: user
              supportsTools: false
              minimumTempature: 1.0
        - name: o3-mini
          model: o3-mini-2025-01-31
          options:
              minimumTempature: 1.0
    Google:
        - name: gemini
          model: gemini-2.0-flash-exp
    Groq:
        - name: llama3-70b
          model: llama3-70b-8192
    Ollama:
        - name: llama3
          model: llama3.3
        - name: qwen
          model: qwen2.5-coder:32b
        - name: r1
          model: MFDoom/deepseek-r1-tool-calling:32b
    DeepSeek:
        - name: deepseek-chat
          model: deepseek-chat
          options:
              systemMessageRole: system
        - name: deepseek-reasoner
          model: deepseek-reasoner
          options:
              systemMessageRole: system
              supportsTools: false
embeddings:
    OpenAI:
        - name: text-embedding-3-small
          model: text-embedding-3-small
          dimensions: 1536
          maxInput: 8191
    Ollama:
        - name: mxbai-embed-large
          model: mxbai-embed-large
          dimensions: 1024
          maxInput: 4096
