defaultModel: sonnet
reprompterModel: haiku
embeddingsModel: mxbai-embed-large
summarizerModel: gpt-4o-mini
relevanceModel: gpt-4o-mini
webTranslatorModel: gpt-4o-mini
shellCommand: zsh

providers:
    Anthropic: { include: ./models/chat/anthropic.yaml }
    DeepSeek: { include: ./models/chat/deepseek.yaml }
    Google: { include: ./models/chat/google.yaml }
    Groq: { include: ./models/chat/groq.yaml }
    Ollama: { include: ./models/chat/ollama.yaml }
    OpenAI: { include: ./models/chat/openai.yaml }
    OpenRouter: { include: ./models/chat/openrouter.yaml }

embeddings:
    Ollama: { include: ./models/embedding/ollama.yaml }
    OpenAI: { include: ./models/embedding/openai.yaml }
